name: Ubuntu Linux gcc Build
on: [push]

# Local mirrors are faster
env:
  REPO_OPENGL: "http://server:3000/Mirror/OpenGL-Registry.git"
  REPO_EGL: "http://server:3000/Mirror/EGL-Registry.git"
  REPO_GLFIXES: "http://server:3000/Mirror/glfixes.git"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          apt update
          apt install -y libxmu-dev libxi-dev libgl-dev libegl1-mesa-dev dos2unix
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: Generate GLEW Sources
        run: |
          make -C auto clobber
          make extensions
          make dist-src
      - name: Build Binaries
        run: |
          make clean && SYSTEM=linux            make
          make clean && SYSTEM=linux-egl        make
