name: Ubuntu Linux cmake Build
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour: [
          "-DGLEW_X11=Y -DGLEW_EGL=N -DBUILD_SHARED_LIBS=N",
          "-DGLEW_X11=N -DGLEW_EGL=Y -DBUILD_SHARED_LIBS=N",
          "-DGLEW_X11=Y -DGLEW_EGL=N -DBUILD_SHARED_LIBS=Y",
          "-DGLEW_X11=N -DGLEW_EGL=Y -DBUILD_SHARED_LIBS=Y",
          ]
    exclude:
      - os: macos-latest
        version: 12
        environment: production
    steps:
      - name: Install Dependencies
        run: |
          apt update
          apt install -y cmake ninja libxmu-dev libxi-dev libgl-dev libegl1-mesa-dev dos2unix
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Generate Code
        run: |
          make -C auto clobber
          make extensions
          make dist-src
      - name: Build Binaries
        run: |
          mkdir build_
          cmake build/cmake -B build_ --fresh ${{ matrix.flavour }}
          rm -Rf build_


