# As of FreeBSD12 X11 is in /usr/local

NAME = $(GLEW_NAME)
CC = cc
LD = ld
LDFLAGS.EXTRA = -L/usr/local/lib
LDFLAGS.GL = -lGL -lX11
LDFLAGS.STATIC = -Wl,-Bstatic
LDFLAGS.DYNAMIC = -Wl,-Bdynamic
CFLAGS.EXTRA += -I/usr/local/include -fPIC
NAME = GLEW
WARN = -Wall -W
POPT = -O2
BIN.SUFFIX =
LIB.SONAME    = lib$(NAME).so.$(SO_MAJOR)
LIB.DEVLNK    = lib$(NAME).so
LIB.SHARED    = lib$(NAME).so.$(SO_VERSION)
LIB.STATIC    = lib$(NAME).a
LDFLAGS.SO    = -shared -soname $(LIB.SONAME)
